dsm/clientfile/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views_clients, views_analysis, views_history, views_groups

app_name = "clientfile"
urlpatterns = [
    path(r"", RedirectView.as_view(url="/clientfile/clients")),
    path(
        r"clients/", views_clients.clients, name="clients"
    ),  # 权限下所有客户
    path(
        r"clients/search/",
        views_clients.client_search,
        name="client_search",
    ),  # 客户搜索
    path(
        r"clients/<int:id>/", views_clients.client_detail, name="client_detail"
    ),  # 单个客户细节
    path(r"import_excel/", views_clients.import_excel, name="import_excel"),  # 导入记录
    path(
        r"export_clients/", views_clients.export_clients, name="export_clients"
    ),  # 导出档案记录
    path(r"analysis/", views_analysis.analysis, name="analysis"),  # 分析现有档案
    path(
        r"ajax_chart", views_analysis.ajax_chart, name="ajax_chart"
    ),  # Ajax出表
    path(r"history/", views_history.history, name="history"),  # 档案记录
#     path(
#         r"groups/export", views_groups.export_groups, name="export_groups"
#     ),  # 导出客户事件记录
#     path(r"groups", views_groups.groups, name="groups"),  # 客户分组事件
#     path(
#         r"groups/<int:id>/", views_groups.group_detail, name="group_detail"
#     ),  # 单个客户分组细节
#     path(r"groups/add", views_groups.add_group, name="add_group"),  # 添加新客户分组事件
#     path(r"groups/delete", views_groups.delete_group, name="delete_group"),  # 删除客户分组事件
]

dsm/dsm/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path("clientfile/", include("clientfile.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("medical_info/", include("medical_info.urls")),
    # path('', views.index, name='index'),
    # path('auth/', include('AuthService.urls')),
]

dsm/clientfile/models.py
from functools import cached_property
from django.db import models
from django.conf import settings
from django.db.models.query import QuerySet
from django.db.models import Q, UniqueConstraint, Max
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import json
from werkzeug.utils import cached_property


@receiver(post_save, sender=User)
def create_staff(sender, instance, created, **kwargs):
    if created:
        Staff.objects.create(user=instance)


class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    position = models.CharField(max_length=30)
    desendants = models.CharField(max_length=999)

    def set_desendants(self, x):
        self.desendants = json.dumps(x)

    def get_desendants(self):
        return json.loads(self.desendants)


class SoftDeleteQuerySet(QuerySet):
    # https://stackoverflow.com/questions/28896237/override-djangos-model-delete-method-for-bulk-deletion
    def __init__(self, *args, **kwargs):
        return super(self.__class__, self).__init__(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for obj in self:
            obj.delete()


class SoftDeletableManager(models.Manager):
    """ Use this manager to get objects that have a is_deleted field """

    def get_queryset(self, *args, **kwargs):
        return SoftDeleteQuerySet(
            model=self.model, using=self._db, hints=self._hints
        ).filter(is_deleted=False)

    def all_with_deleted(self, *args, **kwargs):
        return SoftDeleteQuerySet(
            model=self.model, using=self._db, hints=self._hints
        ).filter()

    def deleted_set(self, *args, **kwargs):
        return SoftDeleteQuerySet(
            model=self.model, using=self._db, hints=self._hints
        ).filter(is_deleted=True)

    def get(self, *args, **kwargs):
        """ if a specific record was requested, return it even if it's deleted """
        return self.all_with_deleted().get(*args, **kwargs)

    def filter(self, *args, **kwargs):
        """ if pk was specified as a kwarg, return even if it's deleted """
        if "pk" in kwargs:
            return self.all_with_deleted().filter(*args, **kwargs)
        return self.get_queryset().filter(*args, **kwargs)

    def max_pub_id(self, *args, **kwargs):
        objs = self.all_with_deleted()
        return objs.aggregate(Max("pub_id"))["pub_id__max"]


class SoftDeletableModel(models.Model):
    is_deleted = models.BooleanField(default=False, verbose_name="软删除")

    class Meta:
        abstract = True

    objects = SoftDeletableManager()

    def delete(self, using=None, soft=True, *args, **kwargs):
        """
        这里需要真删除的话soft=False即可
        """
        if soft:
            self.is_deleted = True
            self.save(using=using)
        else:
            return super(SoftDeletableModel, self).delete(using=using, *args, **kwargs)


HPLEVEL_CHOICES = [
    ("D10", "D10"),
    ("D9", "D9"),
    ("D8", "D8"),
    ("D7", "D7"),
    ("D6", "D6"),
    ("D5", "D5"),
    ("D4", "D4"),
    ("D3", "D3"),
    ("D2", "D2"),
    ("D1", "D1"),
    ("旗舰社区", "旗舰社区"),
    ("普通社区", "普通社区"),
]

PROVINCE_CHOICES = [
    ("北京", "北京"),
    ("天津", "天津"),
    ("河北", "河北"),
    ("山西", "山西"),
    ("内蒙古", "内蒙古"),
    ("辽宁", "辽宁"),
    ("吉林", "吉林"),
    ("黑龙江", "黑龙江"),
    ("上海", "上海"),
    ("江苏", "江苏"),
    ("浙江", "浙江"),
    ("安徽", "安徽"),
    ("福建", "福建"),
    ("江西", "江西"),
    ("山东", "山东"),
    ("河南", "河南"),
    ("湖北", "湖北"),
    ("湖南", "湖南"),
    ("广东", "广东"),
    ("广西", "广西"),
    ("海南", "海南"),
    ("重庆", "重庆"),
    ("四川", "四川"),
    ("贵州", "贵州"),
    ("云南", "云南"),
    ("西藏", "西藏"),
    ("陕西", "陕西"),
    ("甘肃", "甘肃"),
    ("青海", "青海"),
    ("宁夏", "宁夏"),
    ("新疆", "新疆"),
]
DEPT_CHOICES = [
    ("心内科", "心内科"),
    ("肾内科", "肾内科"),
    ("神内科", "神内科"),
    ("内分泌科", "内分泌科"),
    ("老干科", "老干科"),
    ("普内科", "普内科"),
    ("其他科室", "其他科室"),
    ("社区-全科", "社区-全科"),
    ("社区-其他", "社区-其他"),
]
TITLE_CHOICES = [
    ("院长", "院长"),
    ("副院长", "副院长"),
    ("主任医师", "主任医师"),
    ("副主任医师", "副主任医师"),
    ("主治医师", "主治医师"),
    ("住院医师", "住院医师"),
    ("其他", "其他"),
]
BU_CHOICES = [
    ("北中国", "北中国"),
    ("南中国", "南中国"),
]
RD_CHOICES = [
    ("东区", "东区"),
    ("南区", "南区"),
    ("北一区", "北一区"),
    ("北二区", "北二区"),
    ("中区", "中区"),
]


class Client(SoftDeletableModel):
    bu = models.CharField(max_length=10, choices=BU_CHOICES, verbose_name="南北东中国")
    rd = models.CharField(max_length=10, choices=RD_CHOICES, verbose_name="所属区域")
    rm = models.CharField(max_length=10, verbose_name="所属大区")
    dsm = models.CharField(max_length=10, verbose_name="所属经理")
    rsp = models.CharField(max_length=10, verbose_name="负责代表")
    xlt_id = models.CharField(max_length=10, verbose_name="医院编码")
    hospital = models.CharField(max_length=100, verbose_name="医院全称")
    province = models.CharField(
        max_length=10, choices=PROVINCE_CHOICES, verbose_name="省/自治区/直辖市"
    )
    dual_call = models.BooleanField(verbose_name="是否双call")
    hp_level = models.CharField(
        max_length=4, choices=HPLEVEL_CHOICES, verbose_name="医院级别"
    )
    hp_access = models.BooleanField(verbose_name="开户进展")
    dept = models.CharField(max_length=10, choices=DEPT_CHOICES, verbose_name="所在科室")
    name = models.CharField(max_length=10, verbose_name="客户姓名")
    title = models.CharField(max_length=10, choices=TITLE_CHOICES, verbose_name="职称")
    phone = models.IntegerField(verbose_name="客户联系电话", null=True, blank=True)
    consulting_times = models.IntegerField(verbose_name="月出诊次数（半天计）")
    patients_half_day = models.IntegerField(verbose_name="每半天门诊量")
    target_prop = models.IntegerField(verbose_name="相关病人比例(%)")
    # monthly_prescription = models.IntegerField(verbose_name='当前月处方量')
    note = models.CharField(max_length=100, verbose_name="备注", null=True, blank=True)
    pub_date = models.DateTimeField(verbose_name="上传日期", auto_now=True)
    pub_id = models.IntegerField(verbose_name="上传编号")
    pub_user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "客户档案"
        verbose_name_plural = "客户档案"
        ordering = ["bu", "rd", "rm", "dsm", "rsp", "hospital", "dept", "name"]
        # unique_together = ('rsp', 'hospital', 'dept', 'name')
        constraints = [
            UniqueConstraint(
                fields=["rsp", "hospital", "dept", "name"],
                condition=Q(is_deleted=False),
                name="unique_if_not_deleted",
            )
        ]

    def __str__(self):
        return "%s %s %s %s %s %s %s %s" % (
            self.bu,
            self.rd,
            self.rm,
            self.dsm,
            self.rsp,
            self.hospital,
            self.dept,
            self.name,
        )

    @cached_property
    def monthly_patients(self):
        return round(
            self.consulting_times * self.patients_half_day * self.target_prop / 100, 0
        )

    @cached_property
    def potential_level(self):
        if self.monthly_patients < 80:
            return 1
        elif self.monthly_patients < 200:
            return 2
        else:
            return 3

    def updated_status(self):
        if self.is_deleted is True:
            updated_obj = (
                Client.objects.all_with_deleted()
                .filter(
                    hospital=self.hospital,
                    dept=self.dept,
                    name=self.name,
                    is_deleted=False,
                )
                .first()
            )
            if updated_obj is None:
                return "\n档案移除或医院/科室发生变化"
            else:
                if updated_obj.monthly_patients() != self.monthly_patients():
                    return "\n潜力更新为:" + str(updated_obj.monthly_patients())
                return None


class Group(models.Model):
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="created_group",
        verbose_name="创建用户",
    )
    name = models.CharField(max_length=50, verbose_name="分组事件名称")
    clients = models.ManyToManyField(Client, verbose_name="分组事件客户")
    note = models.CharField(max_length=100, verbose_name="备注", null=True, blank=True)
    pub_date = models.DateTimeField(verbose_name="创建日期", auto_now=True)

    class Meta:
        verbose_name = "客户分组事件"
        verbose_name_plural = "客户分组事件"
        ordering = ["-pub_date"]

    def __str__(self):
        return self.name

    def clients_all_with_deleted(self):
        return Client.objects.all_with_deleted().filter(group__id=self.pk)

    def clients_count_with_deleted(self):
        return len(self.clients_all_with_deleted())

    def total_monthly_patients(self):
        monthly_patients = 0
        for client in self.clients_all_with_deleted():
            monthly_patients += client.monthly_patients()
        return monthly_patients

    def avg_monthly_patients(self):
        if self.clients_count_with_deleted() == 0:
            return 0
        else:
            return self.total_monthly_patients() / self.clients_count_with_deleted()


class Hp_IQVIA(models.Model):
    name = models.CharField(max_length=100, verbose_name="医院全称")
    xlt_id = models.CharField(max_length=10, verbose_name="医院编码")
    province = models.CharField(max_length=10, verbose_name="省/自治区/直辖市")
    city = models.CharField(max_length=10, verbose_name="城市")
    potential = models.IntegerField(verbose_name="高血压定义市场潜力")
    potential_rank = models.IntegerField(verbose_name="潜力排名")
    decile = models.IntegerField(verbose_name="潜力十分位")
    is_target = models.BooleanField(verbose_name="是否目标医院")

    class Meta:
        verbose_name = "IQVIA医院潜力评级"
        verbose_name_plural = "IQVIA医院潜力评级"
        ordering = ["potential_rank"]

    def __str__(self):
        return "%s %s %s" % (self.xlt_id, self.name, self.decile)


# class History(models.Model):

dsm/clientfile/templates/clientfile/base.html
<!-- 载入静态文件 -->
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'datatables/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/DataTables-1.10.20/css/dataTables.semanticui.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/FixedHeader-3.1.6/css/fixedHeader.semanticui.min.css' %}">
    <link rel="stylesheet" href="{% static 'Semantic-UI-CSS-master/semantic.min.css' %}">
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'datatables/dataTables.min.js' %}"></script>
    <script src="{% static 'datatables/DataTables-1.10.20/js/dataTables.semanticui.min.js' %}"></script>
    <script src="{% static 'datatables/FixedHeader-3.1.6/js/dataTables.fixedHeader.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'Semantic-UI-CSS-master/semantic.min.js'%}"></script>
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <style type="text/css">
      body {
        background-color: #FFFFFF;
      }
      .ui.menu .item img.logo {
        margin-right: 1.5em;
      }
      .main.container {
        margin-top: 7em;
      }
      .wireframe {
        margin-top: 2em;
      }
      .ui.footer.segment {
        margin: 5em 0em 0em;
        padding: 5em 0em;
      }
      .table {
          max-width: 500px /* sample width. adjust this */
          overflow-x: scroll /* this provides the horizontal scroll */
        }

    </style>


</head>


<body>

{{ navigation }}
<!-- 引入导航栏 -->
{% include 'clientfile/header.html' %}
<!-- 预留具体页面的位置 -->
{% block index %}{% endblock index %}
<!-- 引入注脚 -->
{% include 'clientfile/footer.html' %}

</body>


</html>

dsm/clientfile/templates/clientfile/clients.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "clientfile/base.html" %}
{% load static %}
{% load tags %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
DSM客户档案管理
{% endblock title %}

<!-- 隐藏分隔条 -->
<div class="ui hidden divider">

</div>


<!-- 写入 base.html 中定义的 content -->
{% block index %}
<div id="pusher" class="pusher" style="padding-top:60px">
    <div class="ui hidden divider"></div>
    {% if user.staff.desendants %}
    {% if '地区经理' in user.staff.position %}
    <div class="ui container">
        <h2 class="ui blue dividing header">导入Excel</h2>
        <a href="{% static 'media/客户档案模板.xlsx' %}">下载客户档案模板</a>
        <form class="ui form" enctype="multipart/form-data" id="upload-form" method="post"
            action="{% url 'clientfile:import_excel' %}">
            {% csrf_token %}
            <div class="field">
                <div class="ui action input">
                    <input type="text" id="_attachmentName">
                    <label for="attachmentName" class="ui button btn-file">
                        <i class="upload icon"></i>选择本地Excel
                        <input type="file" id="attachmentName" name="attachmentName" style="display: none"
                            accept="text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                    </label>
                </div>
            </div>
            <input type="button" id="upload" class="ui blue submit button" value="同步数据至平台">
        </form>
        <div class="ui hidden info message" id="msg"></div>
    </div>
    <div class="ui hidden divider"></div>
    {% endif %}
    <div class="ui container">
        <h2 class="ui blue dividing header">现有档案</h2>
        <div class="ui labeled button" tabindex="0">
            <div type="button" class="ui classic blue button" id="export_excel"
                onclick="location.href='{% url 'clientfile:export_clients' %}'">
                <i class="file excel outline icon"></i> 导出至Excel
            </div>
            <a class="ui basic left pointing blue label">
                {{ record_n }}条档案
            </a>
        </div>

        <div class="ui hidden divider"></div>
        <div class="ui container" id='result_table'>
            <table cellpadding="0" cellspacing="0" border="0" id="table" class="ui celled table">
            </table>
        </div>
    </div>

    <div class="ui modal" id="modal_sync_warning">
        <i class="close icon"></i>
        <div class="header">
            警告
        </div>
        <div class="content">
            {% if record_n > 0 %}
            该动作会将本地Excel文件同步至服务器，服务器原有<span style="color: dodgerblue; ">{{ user.username }}</span>的<span
                style="color: dodgerblue; ">{{ record_n }}</span>相关记录将被删除或覆盖
            {% else %}
            该动作会将本地Excel文件同步至服务器
            {% endif %}
        </div>
        <div class="actions">
            <div class="ui black deny button">
                取消
            </div>
            <div class="ui positive right labeled icon button">
                确认同步
                <i class="checkmark icon"></i>
            </div>
        </div>
    </div>

    {% else %}
    <div class="ui middle aligned center aligned grid" style="min-height: 450px;">
        <div class="column" style="max-width: 800px;">
            <div class="ui icon huge negative message">
                <i class="lock icon"></i>
                <div class="content">
                    <div class="header">
                        没有浏览权限
                    </div>
                    <p>如有疑问，请联系管理员</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajaxSetup({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
    });
</script>

<script>
    $(document).ready(function () {
        $("#table").DataTable(
            initDataTable(urlParam, columnsParam)
        )
    });
</script>

<script>
    $("#upload").click(function () {
        $('#modal_sync_warning')
            .modal("setting", {
                closable: false,
                onApprove: function () {
                    var formdata = new FormData(document.getElementById("upload-form"));
                    $("#msg").attr("class", "ui visible info message");
                    $("#msg").html("数据上传中……");
                    $.ajax({
                        url: '{% url 'clientfile:import_excel' %}',
                        type: "post",
                        data: formdata,
                        contentType: false, //- 必须false才会自动加上正确的Content-Type
                        processData: false, //- 必须false才会避开jQuery对 formdata 的默认处理,XMLHttpRequest会对 formdata 进行正确的处理
                        success: function (ret) {
                            if (ret.code === 1) {
                                $("#msg").attr("class", "ui positive message");
                                $("#msg").html(ret.msg);
                                setTimeout(function () {
                                    $('#table').DataTable().ajax.reload(null,
                                        false);
                                }, 1000);
                            } else {
                                $("#msg").attr("class", "ui negative message");
                                $("#msg").html(ret.msg);
                            }
                        },
                        error: function () {
                            $("#msg").attr("class", "ui negative message");
                            $("#msg").html("上传失败，有未知错误发生，请联系管理员");
                        }
                    });
                }
            })
            .modal("show");
    });
</script>


<script>
    // table初始化方法
    function initDataTable(urlParam, columnsParam) {
        return {
            sPaginationType: "full_numbers", //分页风格，full_number会把所有页码显示出来
            searching: true, //搜索
            ordering: true, //是否启用排序
            bProcessing: true, //是否显示加载
            sAjaxSource: urlParam, //请求资源路径
            serverSide: true, //开启服务器处理模式
            /*
                   使用ajax，在服务端处理数据
                   sSource:即是"sAjaxSource"
                   aoData:要传递到服务端的参数
                   fnCallback:处理返回数据的回调函数
                   */
            fnServerData: function (sSource, aoData, fnCallback) {
                console.log("{{ user.staff.desendants }}")
                $.ajax({
                    'type': 'POST',
                    "url": sSource,
                    "dataType": "json",
                    "data": {
                        "aodata": JSON.stringify(aoData),
                        "user_auth": "{{ user.staff.desendants }}",
                    },
                    "success": function (resp) {
                        fnCallback(resp);
                    }
                });
            },
            "oLanguage": { //语言设置
                "sLengthMenu": '<select class="form-control" style="width:150px">' +
                    '<option value="10" selected>每页显示10条</option>' +
                    '<option value="20">每页显示20条</option>' +
                    '<option value="50">每页显示50条</option>' +
                    '<option value="100">每页显示100条</option>' +
                    '</select>',
                "sProcessing": "处理中...",
                "sZeroRecords": "没有匹配结果",
                "sInfo": "显示第 _START_ 至 _END_ 条客户档案，共 _TOTAL_ 条",
                "sInfoEmpty": "没有数据",
                "sInfoFiltered": "(获取 _MAX_ 条客户档案)",
                "sInfoPostFix": "",
                "sSearch": "搜索:",
                "sUrl": "",
                "sEmptyTable": "表中数据为空",
                "sLoadingRecords": "载入中...",
                "sInfoThousands": ",",
                "oPaginate": {
                    "sFirst": "首页",
                    "sPrevious": "上页",
                    "sNext": "下页",
                    "sLast": "末页"
                },
            },
            "bServerSide": true, //开启服务器模式，使用服务器端处理配置datatable。
            "columns": columnsParam,
        }
    }

    var urlParam = '{% url 'clientfile:clients' %}'
    var columnsParam = [{
            title: "南北东中国",
            data: "bu"
        },
        {
            title: "区域",
            data: "rd"
        },
        {
            title: "大区",
            data: "rm"
        },
        {
            title: "地区经理",
            data: "dsm"
        },
        {
            title: "负责代表",
            data: "rsp"
        },
        {
            title: "医院全称",
            data: "hospital"
        },
        {
            title: "医院级别",
            data: "hp_level"
        },
        {
            title: "客户姓名",
            data: "name"
        },
        {
            title: "所在科室",
            data: "dept"
        },
        {
            title: "职称",
            data: "title"
        },
        {
            title: "月出诊半天",
            data: "consulting_times"
        },
        {
            title: "每半天病人数",
            data: "patients_half_day"
        },
        {
            title: "相关病人比例",
            data: "target_prop"
        },
        // {title: "备注", data: "note"},
        {
            title: "月累积病人数",
            data: "monthly_target_patients"
        },
        {
            title: "潜力评级",
            data: "potential_level"
        },
    ];
</script>

<script>
    var fileExtentionRange = '.csv .xls .xlsx';
    var MAX_SIZE = 30; // MB

    $(document).on('change', '.btn-file :file', function () {
        var input = $(this);

        if (navigator.appVersion.indexOf("MSIE") != -1) { // IE
            var label = input.val();

            input.trigger('fileselect', [1, label, 0]);
        } else {
            var label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            var numFiles = input.get(0).files ? input.get(0).files.length : 1;
            var size = input.get(0).files[0].size;

            input.trigger('fileselect', [numFiles, label, size]);
        }
    });

    $('.btn-file :file').on('fileselect', function (event, numFiles, label, size) {
        $('#attachmentName').attr('name', 'attachmentName'); // allow upload.

        var postfix = label.substr(label.lastIndexOf('.'));
        if (fileExtentionRange.indexOf(postfix.toLowerCase()) > -1) {
            if (size > 1024 * 1024 * MAX_SIZE) {
                alert('max size：<strong>' + MAX_SIZE + '</strong> MB.');

                $('#attachmentName').removeAttr('name'); // cancel upload file.
            } else {
                $('#_attachmentName').val(label);
            }
        } else {
            alert('file type：<br/> <strong>' + fileExtentionRange + '</strong>');

            $('#attachmentName').removeAttr('name'); // cancel upload file.
        }
    });
</script>

{% endblock index %}

dsm/clientfile/templates/clientfile/header.html
{% load static %}
{% url 'clientfile:clients' as clients_url %}
{% url 'clientfile:analysis' as analysis_url %}
{% url 'clientfile:history' as history_url %}
{% comment %} {% url 'clientfile:groups' as groups_url %} {% endcomment %}
{% comment %} {% url 'admin:index' as admin_url %} {% endcomment %}

<div class="ui large top fixed inverted menu" id="nav_menu">
    <div class="ui container">
        <div href="#" class="header item">
            <img class="logo" src="{% static 'assets/images/logo.png' %}">
            客户档案管理
        </div>
        <a href="{{ clients_url }}" class="{% if request.get_full_path == clients_url %}active red{% endif %} item">档案管理</a>
        <a href="{{ analysis_url }}"  class="{% if request.get_full_path == analysis_url %}active red{% endif %} item">档案分析</a>
        {% comment %} <a href="{{ groups_url }}"  class="{% if request.get_full_path == groups_url %}active red{% endif %} item">客户分组事件</a> {% endcomment %}
        {% comment %} <a href="{{ history_url }}" class="{% if request.get_full_path == history_url %}active red{% endif %} item">操作记录</a> {% endcomment %}
        {% comment %} <a href="{{ admin_url }}" class="{% if request.get_full_path == admin_url %}active red{% endif %} item">后台管理</a> {% endcomment %}

    </div>
    <div class="right menu">
        {% if request.user.username %}
            <div class="ui item">
                您好，{{ request.user.username }}
            </div>
        {% endif %}
        {% comment %} {%  if not request.user.username  %}
            <div class="ui item">
                未登录
            </div>
        {% else %}
            <div class="ui item">
                您好，{{ request.user.username }}
            </div>
            <a class="ui item" href="{% url 'logout' %}">
                切换用户
            </a>
        {% endif %} {% endcomment %}
  </div>
</div>

<script>
$('.ui.fluid.search.dropdown')
.dropdown();
$('#db_table-select').val('{{ request.session.db_table }}');



</script>
<script>
function submitForm(){
//获取form表单对象
var form = document.getElementById("myform");
form.submit();//form表单提交

}



</script>

dsm/clientfile/templates/clientfile/menu.html
<div class="ui container">
    <div class="ui form">
        <form action="" method="post">
            {% csrf_token %}
            <h3 class="ui header" id="data_filter">数据筛选</h3>
            <div class="field">
                {% for key, value in field_list.items %}
                <div class="field">
                    <select name="{{ value.select }}" id="{{ value.select|slice:":-2" }}" multiple=""
                            class="ui fluid search dropdown">
                        <option value="">{{ key }}</option>
                        {% for item in value.options %}
                            <option value="{{ item }}">{{ item }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% endfor %}
            </div>
            <br>
            <div class="ui buttons">
                <!--<input class="ui button" type="reset" id="reset"/>-->
                <!--<div class="or"></div>-->
                <input class="ui blue button" type='button' id='AJAX_get' value="筛选"/>
            </div>
        </form>
    </div>
</div>


<script>
function submitForm(){
//获取form表单对象
var form = document.getElementById("myform");
form.submit();//form表单提交

}
</script>
<script>
    $('.ui.fluid.search.dropdown')
      .dropdown({ fullTextSearch: true });

</script>