dsm/dsm/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path("clientfile/", include("clientfile.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("medical_info/", include("medical_info.urls")),
    # path('', views.index, name='index'),
    # path('auth/', include('AuthService.urls')),
]

dsm/medical_info/urls.py
from django.urls import include, path
from . import views
# from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'records', views.RecordViewSet)
# router.register(r'tenders', views.TenderViewSet)

app_name = 'medical_info'
urlpatterns = [
    path('', views.posts, name='posts'),
    path(r'posts/<int:pk>', views.post_detail, name='post_detail'), # 文章详情页
    path(r'posts_mail_format/<int:pk>', views.post_mail_format, name='post_mail_format'), # 适合导出到邮件的文章格式
]

dsm/medical_info/models.py
from django.db import models
from django.db.models.base import Model
from taggit.managers import TaggableManager
from uuslug import slugify
import os
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.contrib.auth.models import User


def get_filename(instance, filename):
    slug = instance.post.url_slug
    return "medical_info/%s-%s" % (slug, filename)


def slugify_max(text, max_length=50):
    slug = slugify(text)
    if len(slug) <= max_length:
        return slug
    trimmed_slug = slug[:max_length].rsplit("-", 1)[0]
    if len(trimmed_slug) <= max_length:
        return trimmed_slug
    # First word is > max_length chars, so we have to break it
    return slug[:max_length]


def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


class Nation(models.Model):
    name = models.CharField(verbose_name="国家名称", max_length=50, unique=True)
    code = models.CharField(
        verbose_name="国家代码（用以匹配国旗）参考https://semantic-ui.com/elements/flag.html",
        max_length=50,
        unique=True,
    )  # 用以匹配国旗

    class Meta:
        verbose_name = "国家代码"
        verbose_name_plural = "国家代码"
        ordering = ["name"]

    def __str__(self):
        return "%s (%s)" % (self.name, self.code)


class PubAgent(models.Model):
    full_name = models.CharField(verbose_name="全称", max_length=200, unique=True)
    abbr_name = models.CharField(verbose_name="简称", max_length=100, unique=True)

    class Meta:
        verbose_name = "发布平台"
        verbose_name_plural = "发布平台"
        ordering = ["abbr_name"]

    def __str__(self):
        return "%s (%s)" % (self.abbr_name, self.full_name)


class Program(models.Model):
    name = models.CharField(verbose_name="名称", max_length=50)
    create_date = models.DateField(verbose_name="创建日期")
    vol = models.CharField(verbose_name="期数", max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = "发布栏目"
        verbose_name_plural = "发布栏目"
        ordering = ["-create_date"]

    def __str__(self):
        if self.vol is None:
            return "%s %s" % (str(self.create_date), self.name)
        else:
            return "%s %s (%s)" % (str(self.create_date), self.name, self.vol)


class Post(models.Model):
    title_en = models.CharField(verbose_name="英文标题", max_length=300, blank=True)
    title_cn = models.CharField(verbose_name="中文标题", max_length=300)
    pub_agent = models.ForeignKey(
        PubAgent,
        on_delete=models.CASCADE,
        verbose_name="发布方",
        related_name="pub_agents",
    )
    pub_date = models.DateField(verbose_name="发布日期")
    pub_identifier = models.CharField(verbose_name="识别码", max_length=100)
    nation = models.ManyToManyField(to=Nation, verbose_name="涉及国家", blank=True)
    abstract = models.TextField(verbose_name="摘要")
    link = models.CharField(verbose_name="文献来源链接", max_length=100, unique=True)
    program = models.ForeignKey(
        Program,
        on_delete=models.CASCADE,
        default=None,
        verbose_name="栏目",
        null=True,
        blank=True,
        related_name="programs",
    )
    upload_date = models.DateTimeField(verbose_name="上传日期", default=timezone.now)
    url_slug = models.SlugField(editable=False)
    tags = TaggableManager()
    views = models.IntegerField(verbose_name="阅读量", default=0)
    pub_user = models.ForeignKey(
        User, on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "医学信息"
        verbose_name_plural = "医学信息"
        ordering = ["-upload_date"]

    def __str__(self):
        return "%s %s" % (self.title_cn, self.title_en)

    def save(self, *args, **kwargs):
        if not kwargs.pop("skip_lastupdatetime", False):
            self.lastupdatetime = datetime.datetime.now()
        if self.title_en != "":
            self.url_slug = slugify_max(self.title_en)
        else:
            self.url_slug = slugify_max(self.title_cn)
        super(Post, self).save(*args, **kwargs)


class Images(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, default=None, related_name="images"
    )
    image = models.ImageField(upload_to=get_filename, verbose_name="图片")

    class Meta:
        verbose_name = "上传图片"
        verbose_name_plural = "上传图片"

    def __str__(self):
        return os.path.basename(self.image.name)

    def imagename(self):
        return os.path.basename(self.image.name)


class Files(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, default=None, related_name="files"
    )
    file = models.FileField(upload_to=get_filename, verbose_name="文件")

    class Meta:
        verbose_name = "内容文件"
        verbose_name_plural = "内容文件"

    def __str__(self):
        return os.path.basename(self.file.name)

    def filename(self):
        return os.path.basename(self.file.name)

dsm/medical_info/views.py
from clientfile.templatetags.tags import highlight
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Post, Program, Nation
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q, F, Count
import Levenshtein as lev
from django.core.serializers.json import DjangoJSONEncoder
from taggit.models import Tag

DISPLAY_LENGTH = 10


def get_id_list(param):
    id_list = []
    for id in param:
        if isinstance(id, int) == int:
            id_list.append(id)
        else:
            id_list.append(int(id))

    return id_list


def get_param(params):
    kw_param = params.get("kw")  # 根据空格拆分搜索关键字

    tag_param = params.getlist("tag")  # tag可能多选，需要额外处理
    tag_id_list = get_id_list(tag_param)

    nation_param = params.getlist("nation")  # 国家参数
    nation_id_list = get_id_list(nation_param)

    prog_param = params.get("program")  # 栏目参数

    # 下面部分准备所有高亮关键字
    highlights = {}
    try:
        kw_list = kw_param.split(" ")
    except:
        kw_list = []

    for kw in kw_list:
        highlights[kw] = '<b class="highlight_kw">{}</b>'.format(kw)

    for tag_id in tag_id_list:
        tag = Tag.objects.get(pk=tag_id)
        highlights[tag.name] = '<b class="highlight_tag">{}</b>'.format(tag.name)

    context = {
        "kw": kw_param,
        "tags": tag_id_list,
        "nations": nation_id_list,
        "program": prog_param,
        "highlights": highlights,
    }

    return context


# 首页
@login_required
def posts(request):
    print(request.GET)
    param_dict = get_param(request.GET)

    # 所有医学信息
    posts = Post.objects.all()

    # 根据搜索筛选文章
    kw = param_dict["kw"]
    if kw is not None:
        kw_list = kw.split(" ")

        search_condition = (
            Q(title_cn__icontains=kw_list[0])  # 搜索文章中文名
            | Q(title_en__icontains=kw_list[0])  # 搜索文章英文名
            | Q(pub_agent__full_name__icontains=kw_list[0])  # 搜索发布平台全称
            | Q(pub_agent__abbr_name__icontains=kw_list[0])  # 搜索发布平台简称
            | Q(abstract__icontains=kw_list[0])  # 搜索摘要
            | Q(program__name__icontains=kw_list[0])  # 搜索栏目
            | Q(tags__name__icontains=kw_list[0])  # 搜索标签
        )
        for k in kw_list[1:]:
            search_condition.add(
                Q(title_cn__icontains=k)  # 搜索文章中文名
                | Q(title_en__icontains=k)  # 搜索文章英文名
                | Q(pub_agent__full_name__icontains=k)  # 搜索发布平台全称
                | Q(pub_agent__abbr_name__icontains=k)  # 搜索发布平台简称
                | Q(abstract__icontains=k)  # 搜索摘要
                | Q(program__name__icontains=k)  # 搜索栏目
                | Q(tags__name__icontains=k),  # 搜索标签
                Q.AND,
            )

        search_result = posts.filter(search_condition).distinct()

        #  下方两行代码为了克服MSSQL数据库和Django pagination在distinct(),order_by()等queryset时出现重复对象的bug
        sr_ids = [post.id for post in search_result]
        posts = Post.objects.filter(id__in=sr_ids)

    # 根据栏目筛选文章
    program = param_dict["program"]
    if program is not None:
        posts = posts.filter(program__id=program)

    # Chain filter标签在以上基础上多选筛选文章
    for id in param_dict["tags"]:
        posts = posts.filter(tags__id=id)

    # Chain filter国家在以上基础上多选筛选文章
    for id in param_dict["nations"]:
        posts = posts.filter(nation__id=id)

    paginator = Paginator(posts, DISPLAY_LENGTH)
    page = request.GET.get("page")

    try:
        rows = paginator.page(page)
    except PageNotAnInteger:
        rows = paginator.page(1)
    except EmptyPage:
        rows = paginator.page(paginator.num_pages)

    all_tags = Tag.objects.all()
    all_tags = (
        all_tags.annotate(post_count=Count("post"))
        .distinct()
        .order_by(F("post_count").desc())
    )
    print(len(all_tags))
    filter_tags = Tag.objects.filter(post__in=posts)  # 筛选出所有关联医学信息的tags
    filter_tags = (
        filter_tags.annotate(post_count=Count("post"))
        .distinct()
        .order_by(F("post_count").desc())
    )  # 统计tag关联的医学信息数并按从高到低排序
    print(len(filter_tags))
    all_nations = Nation.objects.all()
    all_nations = all_nations.annotate(post_count=Count("post")).order_by(
        F("post_count").desc()
    )
    print(len(all_nations))
    filter_nations = Nation.objects.filter(post__in=posts)  # 筛选出所有关联医学信息的tags
    filter_nations = filter_nations.annotate(post_count=Count("post")).order_by(
        F("post_count").desc()
    )  # 统计tag关联的医学信息数并按从高到低排序
    print(len(filter_nations))

    context = {
        "posts": rows,
        "num_pages": paginator.num_pages,
        "record_n": paginator.count,
        "display_length": DISPLAY_LENGTH,
        "kw": param_dict["kw"],
        "all_tags": all_tags,
        "filter_tags": filter_tags,
        "tag_selected": Tag.objects.filter(pk__in=param_dict["tags"]),
        "all_nations": all_nations,
        "filter_nations": filter_nations,
        "nation_selected": Nation.objects.filter(pk__in=param_dict["nations"]),
        "program": Program.objects.filter(pk=program).first(),
        "highlights": param_dict["highlights"],
    }

    return render(request, "medical_info/posts.html", context)


@login_required
def post_detail(request, pk):
    post = Post.objects.get(pk=pk)

    key = "viewed_post_%s" % post.id
    if request.session.get(key) is None:
        # 记录浏览量

        post.views = F("views") + 1
        post.save(skip_lastupdatetime=True)
        post.refresh_from_db()
        request.session[key] = True

    # 推荐相似的医学信息
    tags = list(post.tags.values_list("name", flat=True))

    d_distance = {}
    posts_oth = Post.objects.exclude(pk=pk)
    for post_oth in posts_oth:
        d_distance[post_oth.pk] = list(
            post_oth.tags.all().values_list("name", flat=True)  # 准备除本post以外的所有post的tags
        )

    for key, value in d_distance.items():
        d_distance[key] = lev.setratio(tags, value)  # 计算本post和其他任一post的Levenshtein距离

    d_distance = {
        k: v
        for k, v in sorted(
            d_distance.items(), key=lambda item: item[1], reverse=True
        )  # 按Levenshtein距离由高到低排序
    }

    posts_related = Post.objects.filter(
        pk__in=list(d_distance.keys())[:5]
    )  # Levenshtein距离最高的5个posts

    all_tags = Tag.objects.all()
    all_tags = all_tags.annotate(post_count=Count("post")).order_by(
        F("post_count").desc()
    )

    all_nations = Nation.objects.all()
    all_nations = all_nations.annotate(post_count=Count("post")).order_by(
        F("post_count").desc()
    )

    context = {
        "post": post,
        "posts_related": posts_related,
        "all_tags": all_tags,
        "all_nations": all_nations,
    }
    return render(request, "medical_info/post_detail.html", context)


@login_required
def post_mail_format(request, pk):
    post = Post.objects.get(pk=pk)
    # baseurl = request.build_absolute_uri(post.url)
    context = {
        "post": post,
    }
    return render(request, "medical_info/post_mail_format.html", context)

dsm/medical_info/templates/medical_info/post_detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "medical_info/index.html" %}
{% load humanize %}
{% load tags %}
{% load taggit_templatetags2_tags %}

{% block title %}医学信息平台{% endblock title %}

<!-- 隐藏分隔条 -->
<div class="ui hidden divider"></div>

<!-- 写入 base.html 中定义的 body content -->
{% block display %}
    <div class="ui container">
        {% if post %}
            <div class="ui big breadcrumb">
                <a href="{% url "medical_info:posts" %}" class="section">返回首页</a>
            </div>
            <div class="ui divider"></div>
            <div class="item">
                <div class="content">
                    {% if post.title_cn %}
                        <h2 class="ui header">
                            {% comment %} <i class="bookmark outline icon"></i> {% endcomment %}
                            <div class="content">
                                {{ post.title_cn }}
                                {% if post.title_en %}
                                    <div class="sub header">{{ post.title_en }}</div>
                                {% endif %}
                            </div>
                        </h2>
                    {% else %}
                        {% if post.title_en %}
                            <h2 class="ui header">
                                {% comment %} <i class="leanpub icon"></i> {% endcomment %}
                                <div class="content">
                                    {{ post.title_en }}
                                </div>
                            </h2>
                        {% endif %}
                    {% endif %}

                    <div class="meta">
                        <span class="pub_agent" data-tooltip="{{ post.pub_agent.full_name }}"><i>{{ post.pub_agent.abbr_name }}.</i></span>
                        <span class="pub_date"><i>{{ post.pub_date }}</i></span>
                        <span class="pub_identifier"><i>{{ post.pub_identifier }}</i></span>
                        {% for nation in post.nation.all %}
                            <i class="{{ nation.code }} flag" title="{{ nation.name }}"></i>
                        {% endfor %}
                    </div>
                    <div class="description">
                        <p>{{ post.abstract }}</p>
                    </div>
                    <div class="extra">
                        标签：
                        {% for tag in post.tags.all %}
                            {% if tag.name == "含医学部解读" %}
                                <a class="ui red label" href="{% url 'medical_info:posts' %}?tag={{ tag.pk }}">
                                    <i class="info icon"></i>
                                    {{ tag }}
                                </a>
                            {% else %}
                                <a class="ui label" href="{% url 'medical_info:posts' %}?tag={{ tag.pk }}">
                                    {{ tag }}
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="extra">
                        {% if post.program %}
                            <div class="ui pointing basic label">
                            <i class="green check icon"></i>
                            发布于
                            <a class="detail" href="{% url 'medical_info:posts' %}?program={{ post.program.pk }}">{{ post.program.name }}{{ post.program.vol }}</a>
                            </div>
                        {% endif %}
                        <div class="ui basic label">
                        <i class="eye icon"></i> {{ post.views }}
                        </div>
                        {% if request.user.is_staff %}
                            <a class="ui red basic label" href="{% url 'medical_info:post_mail_format' post.pk %}">
                                邮件格式
                            </a>
                            <a class="ui red basic label" href="{% url 'admin:medical_info_post_change' post.pk %}">
                                编辑
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="ui divider"></div>
            <div class="ui top attached tabular menu">
            {% for img in post.images.all %}
                <a class="{% if forloop.first and post.images.all %}active{% endif %} item" data-tab="image{{ forloop.counter0|add:1 }}">图片{% if not forloop.first %}{{ forloop.counter0|add:1 }}{% endif %}</a>
            {% endfor %}
            {% for doc in post.files.all %}
                <a class="{% if forloop.first and not post.images.all %}active{% endif %} item" data-tab="pdf{{ forloop.counter0|add:1 }}">文档{% if not forloop.first %}{{ forloop.counter0|add:1 }}{% endif %}</a>
            {% endfor %}
            </div>
            {% for img in post.images.all %}
                <div class="ui bottom attached {% if forloop.first and post.images.all  %}active{% endif %} tab segment" data-tab="image{{ forloop.counter0|add:1 }}">
                    <a class="ui blue right ribbon label" href="{{ img.image.url }}" target="_blank"><i class="external alternate icon"></i>在新窗口中打开</a>
                    <div class="ui hidden divider"></div>
                    <img src="{{ img.image.url }}" width="100%" height="100%"></img>
                </div>
            {% endfor %}
            {% for doc in post.files.all %}
                <div class="ui bottom attached {% if forloop.first and not post.images.all %}active{% endif %} tab segment" data-tab="pdf{{ forloop.counter0|add:1 }}">
                    <a class="ui blue right ribbon label" href="{{ doc.file.url }}" target="_blank"><i class="external alternate icon"></i>在新窗口中打开</a>
                    <div class="ui hidden divider"></div>
                    <div class="wrapper" id="wrapper{{ forloop.counter0|add:1 }}">
                        <object width="100%" height="768" type="application/pdf" data="{{ doc.file.url }}">
                            <p>如PDF不可见，请尝试使用其他浏览器</p>
                        </object>
                    </div>
                </div>
            {% endfor %}

            <div class="ui divider"></div>
            <h3 header>相关阅读</h3>
            {% for post_related in posts_related %}
                <div class="ui list">
                    <div class="item">
                        <i class="chevron right icon"></i>
                        <div class="content">
                            {% if post_related.title_cn %}
                                <a class="header" href="{% url 'medical_info:post_detail' post_related.pk %}">{{ post_related.title_cn }}</a>
                                {% if post_related.title_en %}
                                    <div class="description">{{ post_related.title_en }}</div>
                                {% endif %}
                            {% else %}
                                {% if post_related.title_en %}
                                    <a class="header" href="{% url 'medical_info:post_detail' post_related.pk %}">{{ post_related.title_en }}</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="ui hidden divider"></div>

<script>
    $(document).ready(function () {
        $('.menu .item')
            .tab({'onVisible':function(){
                $(".wrapper").each(function(){
                    var id = $(this).attr("id")
                    $(this).load(location.href + " #" + id);
                })
            }});
    });
</script>

{% endblock display %}

dsm/medical_info/templates/medical_info/posts.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "medical_info/index.html" %}
{% load humanize %}
{% load tags %}
{% load taggit_templatetags2_tags %}

{% block title %}医学信息平台{% endblock title %}

<!-- 隐藏分隔条 -->
<div class="ui hidden divider"></div>

<!-- 写入 base.html 中定义的 body content -->
{% block display %}

<div class="ui hidden divider"></div>

<div class="ui container">
    {% if posts %}
    <div class="ui dividing header">
        <a href="{% url 'medical_info:posts' %}">所有医学信息</a>
        {% if kw %}
            <a class="ui basic blue label" href="{% url 'medical_info:posts' %}?{% add_query_params request kw=kw %}">
                搜索关键字: {{ kw }}
                <i class="delete icon"></i>
            </a>
        {% endif %}
        {% if tag_selected  %}
            {% for tag in tag_selected %}
                <a class="ui basic red label" href="{% url 'medical_info:posts' %}?{% add_query_params request tag=tag.id %}">
                    标签: {{ tag.name }}
                    <i class="delete icon"></i>
                </a>
            {% endfor %}
        {% endif %}
        {% if nation_selected  %}
            {% for nation in nation_selected %}
                <a class="ui basic purple label" href="{% url 'medical_info:posts' %}?{% add_query_params request nation=nation.id %}">
                    国家: {{ nation.name }}
                    <i class="delete icon"></i>
                </a>
            {% endfor %}
        {% endif %}
        {% if program %}
            <a class="ui basic violet label" href="{% url 'medical_info:posts' %}?{% add_query_params request program=program.id %}">
                栏目: {{ program.name}}
                    {% if program.vol %}
                     {{ program.vol }}
                    {% endif %}
                <i class="delete icon"></i>
            </a>
        {% endif %}
        <span> - 当前显示第
            {{ posts.start_index }}-{{ posts.end_index }} of {{ record_n }}条记录
        </span>
    </div>

    <div class="ui divided items">
        {% for post in posts %}
        <div class="item" id="medical_posts">
            <div class="content">
                {% if post.title_cn %}
                <h2 class="ui header">
                    {% comment %} <i class="bookmark outline icon"></i> {% endcomment %}
                    <div class="content">
                        {% if highlights %}
                        {{ post.title_cn|highlight:highlights }}
                        {% else %}
                        {{ post.title_cn}}
                        {% endif %}
                        {% if post.title_en %}
                        <div class="sub header">
                            {% if highlights %}
                            {{ post.title_en|highlight:highlights }}
                            {% else %}
                            {{ post.title_en}}
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                </h2>
                {% else %}
                {% if post.title_en %}
                <h2 class="ui header">
                    {% comment %} <i class="leanpub icon"></i> {% endcomment %}
                    <div class="content">
                        {% if highlights %}
                        {{ post.title_en|highlight:highlights }}
                        {% else %}
                        {{ post.title_en}}
                        {% endif %}
                    </div>
                </h2>
                {% endif %}
                {% endif %}
                
                <div class="meta">
                    <span class="pub_agent"
                        data-tooltip="{{ post.pub_agent.full_name }}"><i>{{ post.pub_agent.abbr_name }}.</i></span>
                    <span class="pub_date"><i>{{ post.pub_date }}</i></span>
                    <span class="pub_identifier"><i>{{ post.pub_identifier }}</i></span>
                    {% for nation in post.nation.all %}
                    <i class="{{ nation.code }} flag" title="{{ nation.name }}"></i>
                    {% endfor %}
                </div>
                <div class="description">
                    {% if post.images.all %}
                    <div class="ui medium right floated bordered image">
                        <img src="{{ post.images.first.image.url }}">
                    </div>
                    {% endif %}
                    <p>
                        {% if highlights %}
                        {{ post.abstract|highlight:highlights }}
                        {% else %}
                        {{post.abstract}}
                        {% endif %}
                    </p>
                </div>
                <div class="extra">
                    标签：
                    {% for tag in post.tags.all %}
                        {% if tag.name == "含医学部解读" %}
                            <a class="ui red label" href="{% url 'medical_info:posts' %}?tag={{ tag.pk }}">
                                <i class="info icon"></i>
                                {{ tag }}
                            </a>
                        {% else %}
                            <a class="ui label" href="{% url 'medical_info:posts' %}?tag={{ tag.pk }}">
                                {{ tag }}
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="extra">
                    <a class="ui right floated primary basic button" data-tooltip="{{ post.link }}"
                        href="{{ post.link }}" target="_blank">
                        文献来源链接
                        <i class="right chevron icon"></i>
                    </a>
                    <a class="ui right floated primary button" href="{% url 'medical_info:post_detail' post.pk %}">
                        阅读PDF原文
                        <i class="right chevron icon"></i>
                    </a>
                    
                    <div class="ui pointing basic label">
                        <i class="green check icon"></i>
                        {{ post.pub_user.username }}
                        {% if post.program %}
                        发布于
                        <a class="detail" href="{% url 'medical_info:posts' %}?program={{ post.program.pk }}">{{ post.program.name }}{{ post.program.vol }}</a>
                        {% else %}
                        发布
                        {% endif %}
                    </div>
                    
                    <div class="ui basic label">
                        <i class="eye icon"></i> {{ post.views }}
                    </div>
                    {% if perms.medical_info.change_post %}
                        {% comment %} <a class="ui red basic label" href="{% url 'medical_info:post_mail_format' post.pk %}">
                            邮件格式
                        </a> {% endcomment %}
                        <a class="ui red basic label" href="{% url 'admin:medical_info_post_change' post.pk %}">
                            编辑
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="ui pagination menu">
        <a class="item" href="{% url 'medical_info:posts' %}?{% add_query_params request page=1 %}">&lt;&lt;</a>

        {% if posts.number|add:'-4' > 1 %}
        <a class="item"
            href="{% url 'medical_info:posts' %}?{% add_query_params request page=posts.number|add:'-5' %}">&hellip;</a>
        {% endif %}


        {% for n in num_pages|times %}
        {% if n == posts.number %}
        <span class="active item"
            href="{% url 'medical_info:posts' %}?{% add_query_params request page=n %}">{{ n }}</span>
        {% elif n > posts.number|add:'-5' and n < posts.number|add:'5' %}
        <a class="item" href="{% url 'medical_info:posts' %}?{% add_query_params request page=n %}">{{ n }}</a>
        {% endif %}
        {% endfor %}


        {% if num_pages > posts.number|add:'4' %}
        <a class="item"
            href="{% url 'medical_info:posts' %}?{% add_query_params request page=posts.number|add:'5' %}">&hellip;</a>
        {% endif %}

        <a class="item"
            href="{% url 'medical_info:posts' %}?{% add_query_params request page=num_pages %}">&gt;&gt;</a>
    </div>
    {% else %}
    <div class="ui error message">
        没有搜索到符合条件的记录，返回<a href="{% url 'medical_info:posts' %}">所有医学信息</a>
    </div>
    {% endif %}
</div>
<div class="ui hidden divider"></div>

<style>
    .highlight_kw {
        background-color: #FFEFC5;
    }
    .highlight_tag {
        background-color: #BEF3D8;
    }
</style>
{% endblock display %}

dsm/medical_info/templates/medical_info/programs.html
{% regroup programs by create_date.year as year_list %}

<div class="ui segment">
    <div class="ui list">
        <div class="item">
            <i class="info red icon"></i>
            <div class="content">
                <a href="{% url 'medical_info:posts' %}?tag=255">含医学部解读的文章</a>
            </div>
        </div>
        <div class="item">
            <i class="star outline orange icon"></i>
            <div class="content">
                <a href="{% url 'medical_info:posts' %}?program=15">个人分享</a>
            </div>
        </div>
    </div>
</div>
{% for year in year_list %}
<div class="ui segment">
    <a class="ui top left attached label">{{ year.grouper }}</a>
    <div class="ui list">
        {% for program in year.list %}
            {% if program.name != '个人分享' %}
                <div class="item">
                    <i class="ellipsis vertical icon"></i>
                    <div class="content">
                        <a href="{% url 'medical_info:posts' %}?program={{ program.pk }}">{{ program.name}}
                            {% if program.vol %}
                            {{ program.vol }}
                            {% endif %}
                            ({{ program.post_count }})
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endfor%}